name: client_filtering
description: Allows dynamic client filtering through a set of models
version: 0.0.26
homepage: https://github.com/4D-Technologies/responsive_data_grid/client_filtering
repository: https://github.com/4D-Technologies/responsive_data_grid

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  darq: ^1.2.1

dev_dependencies:
  lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
