name: client_filtering
description: Allows dynamic client filtering through a set of models
version: 0.0.18
homepage: https://github.com/Concerti-IO/responsive_data_grid/client_filtering
repository: https://github.com/Concerti-IO/responsive_data_grid

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
