name: client_filtering
description: Allows dynamic client filtering through a set of models
version: 0.0.26
homepage: https://github.com/4D-Technologies/responsive_data_grid/client_filtering
repository: https://github.com/4D-Technologies/responsive_data_grid

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  darq: ^2.0.0
  intl: ^0.17.0
  odata_query: ^2.3.0

dev_dependencies:
  lints: ^5.1.1
  flutter_test:
    sdk: flutter
