name: client_filtering
description: Allows dynamic client filtering through a set of models
version: 0.0.15
homepage: https://github.com/Concerti-IO/responsive_data_grid/client_filtering
repository: https://github.com/Concerti-IO/responsive_data_grid

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter

flutter:
