name: example
description: Example project for Responsive Data Grid.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:

  responsive_data_grid:
    path: ../

  client_filtering:
    path: ../../client_filtering

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
