name: example
description: Example project for Responsive Data Grid.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.20.2 <1.0.0"

  responsive_data_grid:
    path: ../

  client_filtering: ^0.0.29

  cupertino_icons: ">=1.0.8 <2.0.0"
  material_ui: ">=1.1.0 <2.0.0"

dependency_overrides:
  client_filtering:
    path: ../../client_filtering

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
