name: example
description: Example project for Responsive Data Grid.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  client_filtering: ^0.0.20
  responsive_data_grid:
    path: ../

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
