name: responsive_data_grid
description: Responsive Data Grid for Flutter inspired by Kendo UI's Grid functionality with full filtering, sorting, and paging that also responds dynamically to screen size using the same metaphor as bootstrap grid.
version: 1.0.2
homepage: https://github.com/4D-Technologies/responsive_data_grid/tree/main/responsive_data_grid
repository: https://github.com/4D-Technologies/responsive_data_grid

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.10.0 <1.0.0"

  darq: ^2.0.0
  bootstrap_grid: ^1.0.5
  date_field: ^6.0.3
  infinite_scroll_pagination: ^5.0.0

  client_filtering: ^0.0.28

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
