name: responsive_data_grid
description: Responsive Data Grid for Flutter inspired by Kendo UI's Grid functionality with full filtering, sorting, and paging that also responds dynamically to screen size using the same metaphor as bootstrap grid.
version: 1.0.1
homepage: https://github.com/4D-Technologies/responsive_data_grid/tree/main/responsive_data_grid
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:

  darq: ^2.0.0
  bootstrap_grid: ^1.0.5
  date_field: ^6.0.0
  infinite_scroll_pagination: ^4.1.0

  client_filtering:
    path: ../client_filtering

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
