name: responsive_data_grid
description: Responsive Data Grid for Flutter inspired by Kendo UI.
version: 0.0.6
homepage: https://github.com/Concerti-IO/responsive_data_grid/responsive_data_grid
repository: https://github.com/Concerti-IO/responsive_data_grid

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  bootstrap_grid: ^1.0.1
  client_filtering: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
